#!/bin/bash

gcc jiami.c -lpthread -o jiami

 ./jiami -f a -d /home/mayday/Desktop/linux_test/C/hong/1/ -o /home/mayday/Desktop/linux_test/C/hong/2/ -e
./jiami -f a -o /home/mayday/Desktop/linux_test/C/hong/1/ -d /home/mayday/Desktop/linux_test/C/hong/2/ -s

